//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.2034
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetaConstructor.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MetaConstructor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MetaConstructor.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon Circle_add {
            get {
                object obj = ResourceManager.GetObject("Circle_add", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Circle_apply {
            get {
                object obj = ResourceManager.GetObject("Circle_apply", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Circle_arrow {
            get {
                object obj = ResourceManager.GetObject("Circle_arrow", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Circle_fire {
            get {
                object obj = ResourceManager.GetObject("Circle_fire", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Circle_group {
            get {
                object obj = ResourceManager.GetObject("Circle_group", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CircleField {
            get {
                object obj = ResourceManager.GetObject("CircleField", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CircleGold {
            get {
                object obj = ResourceManager.GetObject("CircleGold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CircleLime {
            get {
                object obj = ResourceManager.GetObject("CircleLime", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CircleSelected {
            get {
                object obj = ResourceManager.GetObject("CircleSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CircleViolet {
            get {
                object obj = ResourceManager.GetObject("CircleViolet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CircleWhite {
            get {
                object obj = ResourceManager.GetObject("CircleWhite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на USE master;
        ///EXEC sp_attach_db @dbname= N&apos;m_CRM&apos;, @filename1= N&apos;{0}\m_CRM.mdf&apos;;.
        /// </summary>
        internal static string CrmAttachDb {
            get {
                return ResourceManager.GetString("CrmAttachDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на USE master;
        ///
        ///IF  EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE name = N&apos;m_CRM&apos;)
        ///	BEGIN
        ///		DROP DATABASE [m_CRM];
        ///		PRINT &apos;Dropped&apos;;
        ///	END
        ///
        ///CREATE DATABASE [m_CRM]
        ///	ON (NAME = m_CRM,
        ///	FILENAME = N&apos;{0}\m_CRM.mdf&apos;);
        ///
        ///PRINT &apos;Created&apos;;.
        /// </summary>
        internal static string CrmCreateDb {
            get {
                return ResourceManager.GetString("CrmCreateDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на USE m_CRM;
        ///
        ///--Create table of Objects
        ///IF OBJECT_ID(&apos;dbo.Objects&apos;,&apos;U&apos;) IS NOT NULL
        ///	DROP TABLE dbo.Objects;
        ///
        ///CREATE TABLE dbo.Objects
        ///(
        ///	idr 	INT 		NOT NULL,
        ///	hid 	HierarchyId NOT NULL,
        ///	code 	nvarchar(9)	NOT NULL,
        ///	descr	nvarchar(25)NOT NULL,
        ///	CONSTRAINT PK_Objects
        ///		PRIMARY KEY (idr)
        ///);
        ///
        ///--Creating catalog sp21 Features
        ///CREATE TABLE dbo.sp21
        ///(
        ///	idr		int			NOT NULL,
        ///	--hid		HierarchyId NOT NULL,
        ///	--code	nvarchar(9) NOT NULL,
        ///	--descr	nvarchar(25),
        ///	fld32	int			, --TRef19__sp3_Catalog        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string CrmCreateTables {
            get {
                return ResourceManager.GetString("CrmCreateTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на USE master;
        ///IF  EXISTS (
        ///	SELECT * FROM master.dbo.sysdatabases WHERE name = N&apos;m_CRM&apos;
        ///)
        ///	BEGIN
        ///		DROP DATABASE [m_CRM];
        ///		PRINT &apos;Dropped&apos;;
        ///	END
        ///.
        /// </summary>
        internal static string CrmDeleteDb {
            get {
                return ResourceManager.GetString("CrmDeleteDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на USE master;
        ///IF  EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE name = N&apos;m_CRM&apos;)
        ///	BEGIN
        ///		EXEC sp_detach_db [m_CRM];
        ///		PRINT &apos;Detached&apos;;	
        ///	END
        ///;.
        /// </summary>
        internal static string CrmDetachDb {
            get {
                return ResourceManager.GetString("CrmDetachDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на USE m_CRM;
        ///
        ///-- Check that the table is exist
        ///IF OBJECT_ID(&apos;dbo.Objects&apos;, &apos;U&apos;) IS NULL
        ///	RAISERROR(&apos;Table Objects is not exist!&apos;, 16, 1);
        ///
        ///INSERT INTO dbo.Objects
        ///VALUES 
        ///	( 1, 	CAST(&apos;/1/&apos; 		AS HierarchyId), 	N&apos;sys&apos;, 	N&apos;Structure&apos;),
        ///	( 2, 	CAST(&apos;/2/&apos; 		AS HierarchyId), 	N&apos;_cn&apos;, 	N&apos;Constants&apos;),
        ///	( 3, 	CAST(&apos;/3/&apos; 		AS HierarchyId), 	N&apos;_sp&apos;, 	N&apos;Catalogs&apos;),
        ///	( 4,	CAST(&apos;/4/&apos; 		AS HierarchyId), 	N&apos;_dc&apos;, 	N&apos;Documents&apos;),
        ///	( 5,	CAST(&apos;/5/&apos; 		AS HierarchyId), 	N&apos;_sq&apos;, 	N&apos;Sequences&apos;),
        ///	( 6,	CAST(&apos;/6/&apos; 		AS H [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string CrmFillTables {
            get {
                return ResourceManager.GetString("CrmFillTables", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon Data_Objects {
            get {
                object obj = ResourceManager.GetObject("Data_Objects", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose an element!.
        /// </summary>
        internal static string ErrMsgChooseElement {
            get {
                return ResourceManager.GetString("ErrMsgChooseElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can not delete! Element has a link in the other tables!.
        /// </summary>
        internal static string ErrMsgElementHasLink {
            get {
                return ResourceManager.GetString("ErrMsgElementHasLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string frmButtonCancelText {
            get {
                return ResourceManager.GetString("frmButtonCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        internal static string frmButtonCloseText {
            get {
                return ResourceManager.GetString("frmButtonCloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        internal static string frmButtonDeleteText {
            get {
                return ResourceManager.GetString("frmButtonDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export.
        /// </summary>
        internal static string frmButtonExportText {
            get {
                return ResourceManager.GetString("frmButtonExportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load.
        /// </summary>
        internal static string frmButtonLoadText {
            get {
                return ResourceManager.GetString("frmButtonLoadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create.
        /// </summary>
        internal static string frmButtonNewText {
            get {
                return ResourceManager.GetString("frmButtonNewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        internal static string frmButtonSaveText {
            get {
                return ResourceManager.GetString("frmButtonSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Catalog.
        /// </summary>
        internal static string frmCatalogText {
            get {
                return ResourceManager.GetString("frmCatalogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Property.
        /// </summary>
        internal static string frmClmnHdrPropType {
            get {
                return ResourceManager.GetString("frmClmnHdrPropType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value.
        /// </summary>
        internal static string frmClmnHdrPropValue {
            get {
                return ResourceManager.GetString("frmClmnHdrPropValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Code.
        /// </summary>
        internal static string frmCodeText {
            get {
                return ResourceManager.GetString("frmCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        internal static string frmDescrText {
            get {
                return ResourceManager.GetString("frmDescrText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type:.
        /// </summary>
        internal static string frmFeatureKindText {
            get {
                return ResourceManager.GetString("frmFeatureKindText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Feature.
        /// </summary>
        internal static string frmFeaturesText {
            get {
                return ResourceManager.GetString("frmFeaturesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value:.
        /// </summary>
        internal static string frmFeatureValueText {
            get {
                return ResourceManager.GetString("frmFeatureValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Object:.
        /// </summary>
        internal static string frmObjectText {
            get {
                return ResourceManager.GetString("frmObjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select element.
        /// </summary>
        internal static string frmTipsSelectElement {
            get {
                return ResourceManager.GetString("frmTipsSelectElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        internal static string frmToolMenuAdd {
            get {
                return ResourceManager.GetString("frmToolMenuAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        internal static string frmToolMenuDelete {
            get {
                return ResourceManager.GetString("frmToolMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        internal static string frmToolMenuEdit {
            get {
                return ResourceManager.GetString("frmToolMenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Def: Hello, World!.
        /// </summary>
        internal static string HelloString {
            get {
                return ResourceManager.GetString("HelloString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Changes have been saved.
        /// </summary>
        internal static string InfoMsgChangesSaved {
            get {
                return ResourceManager.GetString("InfoMsgChangesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can not create database!.
        /// </summary>
        internal static string InfoMsgDbCanNotCreate {
            get {
                return ResourceManager.GetString("InfoMsgDbCanNotCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can not delete database!.
        /// </summary>
        internal static string InfoMsgDbCanNotDelete {
            get {
                return ResourceManager.GetString("InfoMsgDbCanNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Database created successfully!.
        /// </summary>
        internal static string InfoMsgDbCreated {
            get {
                return ResourceManager.GetString("InfoMsgDbCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Database deleted successfully!.
        /// </summary>
        internal static string InfoMsgDbDeleted {
            get {
                return ResourceManager.GetString("InfoMsgDbDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Opening connection ....
        /// </summary>
        internal static string InfoStatusConnOpening {
            get {
                return ResourceManager.GetString("InfoStatusConnOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attaching database....
        /// </summary>
        internal static string InfoStatusDbAttaching {
            get {
                return ResourceManager.GetString("InfoStatusDbAttaching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Database created successfully.
        /// </summary>
        internal static string InfoStatusDbCreated {
            get {
                return ResourceManager.GetString("InfoStatusDbCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Creating database....
        /// </summary>
        internal static string InfoStatusDbCreating {
            get {
                return ResourceManager.GetString("InfoStatusDbCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Deleting database....
        /// </summary>
        internal static string InfoStatusDbDeleteing {
            get {
                return ResourceManager.GetString("InfoStatusDbDeleteing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Detaching database....
        /// </summary>
        internal static string InfoStatusDbDetaching {
            get {
                return ResourceManager.GetString("InfoStatusDbDetaching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ready.
        /// </summary>
        internal static string InfoStatusReady {
            get {
                return ResourceManager.GetString("InfoStatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Creating tables....
        /// </summary>
        internal static string InfoStatusTablesCreating {
            get {
                return ResourceManager.GetString("InfoStatusTablesCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filling tables....
        /// </summary>
        internal static string InfoStatusTablesFilling {
            get {
                return ResourceManager.GetString("InfoStatusTablesFilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading table {0}....
        /// </summary>
        internal static string InfoStatusTablesLoading {
            get {
                return ResourceManager.GetString("InfoStatusTablesLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning!.
        /// </summary>
        internal static string MsgWarning {
            get {
                return ResourceManager.GetString("MsgWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete {0}?.
        /// </summary>
        internal static string QstMsgDelete {
            get {
                return ResourceManager.GetString("QstMsgDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete database?.
        /// </summary>
        internal static string QstMsgDeleteDB {
            get {
                return ResourceManager.GetString("QstMsgDeleteDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete feature from {0}?.
        /// </summary>
        internal static string QstMsgDeleteElement {
            get {
                return ResourceManager.GetString("QstMsgDeleteElement", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
